name: Create EventBridge Rule for Console Login

on:
  workflow_dispatch:  # Run manually from GitHub Actions

jobs:
  deploy-eventbridge-rule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
      
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run the bash script
        run: bash cloudwatch/setup-eventbridge.sh

